"""Self-contained HTML report generator. Reads classify (and optional
basecomp) JSONs and emits a single HTML file with embedded base64 PNGs,
plus mechanism legend, executive summary, and per-bucket tables.

No JS, no CDN, no external CSS. `string.Template` + stdlib base64."""

import base64
import os
from html import escape
from string import Template

from tecap import __version__
from tecap.constants import (
    BUCKET_COLORS,
    BUCKET_DEFINITIONS,
    BUCKETS,
    CATEGORIES,
    COLORS,
    MECH_A_CORRECT,
    MECH_B_APA,
    MECHANISM_DEFINITIONS,
    PLOT_CAPTIONS,
    SCHEMA_VERSION,
)
from tecap.io import read_json
from tecap.plotting import (
    plot_comparison_basecomp,
    plot_comparison_classify,
    plot_histograms_basecomp,
)

_CSS = """
body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
       max-width: 1100px; margin: 2em auto; padding: 0 1.5em; color: #222;
       line-height: 1.5; }
h1   { border-bottom: 2px solid #333; padding-bottom: .3em; }
h2   { border-bottom: 1px solid #ccc; padding-bottom: .2em; margin-top: 2em; }
h3   { margin-top: 1.5em; }
table { border-collapse: collapse; margin: .5em 0 1em; width: 100%;
        font-size: 0.95em; }
th, td { padding: 6px 10px; text-align: left; border-bottom: 1px solid #eee;
         vertical-align: top; }
th    { background: #f5f5f5; font-weight: 600; }
td.num, th.num { text-align: right; font-variant-numeric: tabular-nums; }
.summary-grid { display: grid; grid-template-columns: repeat(4, 1fr);
                gap: 1em; margin: 1em 0 2em; }
.tile { background: #f6f8fa; border-left: 4px solid #2ecc71; padding: 1em;
        border-radius: 4px; }
.tile .label { font-size: 0.85em; color: #666; text-transform: uppercase;
               letter-spacing: 0.5px; }
.tile .value { font-size: 1.8em; font-weight: 700; margin-top: .2em; }
.swatch { display: inline-block; width: 14px; height: 14px;
          border-radius: 2px; vertical-align: middle; margin-right: 6px;
          border: 1px solid #00000022; }
img.plot { max-width: 100%; height: auto; border: 1px solid #ddd;
           border-radius: 3px; margin: .5em 0; background: white; }
.caption { font-style: italic; color: #555; font-size: 0.9em;
           margin: .2em 0 1em; }
.cmd { font-family: ui-monospace, "SF Mono", Menlo, monospace;
       background: #f6f8fa; padding: .5em .8em; border-radius: 3px;
       font-size: 0.85em; overflow-x: auto; white-space: pre-wrap;
       word-break: break-all; }
footer { color: #777; font-size: 0.85em; margin-top: 3em;
         border-top: 1px solid #eee; padding-top: 1em; }
"""


_TEMPLATE = Template("""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>$title</title>
<style>$css</style>
</head>
<body>
$body
<footer>
Generated by tecap $version (schema $schema). Cite via DOI
<a href="https://doi.org/10.5281/zenodo.19762736">10.5281/zenodo.19762736</a>.
</footer>
</body>
</html>
""")


def _embed_png(path):
    with open(path, "rb") as f:
        b = base64.b64encode(f.read()).decode("ascii")
    return f'<img class="plot" src="data:image/png;base64,{b}" alt="{escape(os.path.basename(path))}">'


def _maybe_embed_png(path):
    if path and os.path.exists(path):
        return _embed_png(path)
    return f'<p class="caption">[plot not found: {escape(path or "")}]</p>'


def _fmt_int(x):
    return "-" if x is None else f"{x:,}"


def _mechanism_legend_html():
    rows = []
    for cat in CATEGORIES:
        d = MECHANISM_DEFINITIONS[cat]
        sw = COLORS[cat]
        rows.append(
            "<tr>"
            f"<td><span class='swatch' style='background:{sw}'></span>"
            f"<strong>{escape(d['short'])}</strong><br>"
            f"<span style='color:#777;font-size:0.85em'>{escape(cat)}</span></td>"
            f"<td>{escape(d['what'])}</td>"
            f"<td>{escape(d['why'])}</td>"
            "</tr>"
        )
    return (
        "<table><thead><tr><th>Bucket</th><th>What it means</th>"
        "<th>Why it matters</th></tr></thead><tbody>"
        + "".join(rows) + "</tbody></table>"
    )


def _bucket_legend_html():
    rows = []
    for b in BUCKETS:
        d = BUCKET_DEFINITIONS[b]
        sw = BUCKET_COLORS[b]
        rows.append(
            "<tr>"
            f"<td><span class='swatch' style='background:{sw}'></span>"
            f"<strong>{escape(b)}</strong></td>"
            f"<td>{escape(d['what'])}</td>"
            f"<td>{escape(d['why'])}</td>"
            "</tr>"
        )
    return (
        "<table><thead><tr><th>Bucket</th><th>What it means</th>"
        "<th>Why it matters</th></tr></thead><tbody>"
        + "".join(rows) + "</tbody></table>"
    )


def _classify_table(summary):
    counts = summary["counts"]
    fractions = summary["fractions"]
    total = summary["total"]
    rows = []
    for cat in CATEGORIES:
        c = counts.get(cat, 0)
        f = fractions.get(cat, 0) * 100
        rows.append(
            "<tr>"
            f"<td><span class='swatch' style='background:{COLORS[cat]}'></span>"
            f"{escape(MECHANISM_DEFINITIONS[cat]['short'])}</td>"
            f"<td class='num'>{c:,}</td>"
            f"<td class='num'>{f:.2f}%</td>"
            "</tr>"
        )
    rows.append(
        f"<tr><td><strong>TOTAL</strong></td>"
        f"<td class='num'><strong>{total:,}</strong></td>"
        f"<td class='num'><strong>100.00%</strong></td></tr>"
    )
    return (
        "<table><thead><tr><th>Mechanism</th><th class='num'>Reads</th>"
        "<th class='num'>%</th></tr></thead><tbody>"
        + "".join(rows) + "</tbody></table>"
    )


def _pas_table(summary):
    pas = summary.get("pas_counts") or {}
    if not pas:
        return ""
    rows = []
    for cat in (MECH_A_CORRECT, MECH_B_APA):
        d = pas.get(cat) or {}
        p = d.get("pas", 0)
        n = d.get("nopas", 0)
        tot = p + n
        if not tot:
            continue
        rows.append(
            f"<tr><td>{escape(MECHANISM_DEFINITIONS[cat]['short'])}</td>"
            f"<td class='num'>{p:,}</td>"
            f"<td class='num'>{p/tot*100:.1f}%</td>"
            f"<td class='num'>{n:,}</td>"
            f"<td class='num'>{n/tot*100:.1f}%</td>"
            f"<td class='num'>{tot:,}</td></tr>"
        )
    if not rows:
        return ""
    return (
        "<table><thead><tr><th>Mechanism</th>"
        "<th class='num'>PAS+</th><th class='num'>PAS+ %</th>"
        "<th class='num'>PAS-</th><th class='num'>PAS- %</th>"
        "<th class='num'>Total</th></tr></thead><tbody>"
        + "".join(rows) + "</tbody></table>"
    )


def _utr_table(summary):
    labels = summary.get("utr_bin_labels") or []
    if not labels:
        return ""
    rows = []
    for i, lbl in enumerate(labels):
        rows.append(
            f"<tr><td>{escape(lbl)} bp</td>"
            f"<td class='num'>{summary['utr_bin_total'][i]:,}</td>"
            f"<td class='num'>{summary['utr_bin_capt_rate'][i]*100:.1f}%</td>"
            f"<td class='num'>{summary['utr_bin_mecha_rate'][i]*100:.1f}%</td></tr>"
        )
    return (
        "<table><thead><tr><th>UTR length bin</th>"
        "<th class='num'>Reads</th>"
        "<th class='num'>Captured rate</th>"
        "<th class='num'>MechA-correct rate</th></tr></thead><tbody>"
        + "".join(rows) + "</tbody></table>"
    )


def _basecomp_table(bc):
    rows = []
    for b in BUCKETS:
        d = bc["buckets"].get(b) or {}
        n = d.get("n", 0)
        if n == 0:
            rows.append(
                f"<tr><td><span class='swatch' style='background:{BUCKET_COLORS[b]}'></span>"
                f"{escape(b)}</td><td class='num'>0</td>"
                f"<td class='num'>-</td><td class='num'>-</td><td class='num'>-</td></tr>"
            )
            continue
        rows.append(
            f"<tr><td><span class='swatch' style='background:{BUCKET_COLORS[b]}'></span>"
            f"{escape(b)}</td>"
            f"<td class='num'>{n:,}</td>"
            f"<td class='num'>{d['median']*100:.1f}%</td>"
            f"<td class='num'>{d['frac_ge_60']*100:.1f}%</td>"
            f"<td class='num'>{d['frac_30_50']*100:.1f}%</td></tr>"
        )
    return (
        "<table><thead><tr><th>Bucket</th>"
        "<th class='num'>n</th>"
        "<th class='num'>Median %A</th>"
        "<th class='num'>&gt;=60% A</th>"
        "<th class='num'>30-50% A</th></tr></thead><tbody>"
        + "".join(rows) + "</tbody></table>"
    )


def _summary_tile(label, value, color="#2ecc71"):
    return (f"<div class='tile' style='border-left-color:{color}'>"
            f"<div class='label'>{escape(label)}</div>"
            f"<div class='value'>{escape(value)}</div></div>")


def _executive_summary(summary):
    fractions = summary.get("fractions") or {}
    pas_frac = summary.get("pas_fraction") or {}
    orient = summary.get("orient_match_frac")

    capt = fractions.get("Captured (>=50%)", 0) * 100
    mecha = fractions.get("MechA-correct: in TE UTR, at polyA site, too short", 0) * 100
    mechb_a = fractions.get("MechB-aspecific: upstream TE, intronic/flanking", 0) * 100
    mecha_pas = pas_frac.get(MECH_A_CORRECT)

    tiles = [
        _summary_tile("Captured", f"{capt:.1f}%", "#2ecc71"),
        _summary_tile("MechA-correct", f"{mecha:.1f}%", "#27ae60"),
        _summary_tile("MechB-aspecific", f"{mechb_a:.1f}%", "#8e44ad"),
        _summary_tile("Orient match",
                      f"{orient:.3f}" if orient is not None else "-", "#3498db"),
    ]
    if mecha_pas is not None:
        tiles.append(_summary_tile("MechA PAS+ frac",
                                   f"{mecha_pas:.3f}", "#27ae60"))
    return f"<div class='summary-grid'>{''.join(tiles)}</div>"


def _resolve_png(json_path, suffix, out_dir, regen=None):
    """Find {sample}_<suffix>.png next to the JSON or in out_dir; if missing
    and a `regen` callable was given, call it to produce the file."""
    base = os.path.dirname(os.path.abspath(json_path))
    sample = os.path.basename(json_path).replace(f"_{suffix}.json", "")
    for d in (base, out_dir):
        if not d:
            continue
        cand = os.path.join(d, f"{sample}_{suffix}.png")
        if os.path.exists(cand):
            return cand
    if regen is not None:
        return regen()
    return None


def build_single_report(classify_json, basecomp_json=None, out_dir=None):
    summary = read_json(classify_json)
    sample = summary.get("sample", "sample")
    out_dir = out_dir or os.path.dirname(os.path.abspath(classify_json))

    classify_png = _resolve_png(classify_json, "terminal_exon", out_dir)
    scatter_png = _resolve_png(classify_json, "mecha_scatter", out_dir)

    bc_summary = None
    bc_png = None
    if basecomp_json:
        bc_summary = read_json(basecomp_json)
        # Always regenerate the basecomp PNG so its formatting matches the
        # current tecap version. The JSON has every field plot_histograms_basecomp
        # needs.
        plot_histograms_basecomp(bc_summary, sample,
                                 out_dir, bc_summary.get("window", 20))
        bc_png = os.path.join(out_dir, f"{sample}_basecomp.png")

    cmd_line = summary.get("command_line", "(not recorded)")

    parts = [
        f"<h1>tecap report — {escape(sample)}</h1>",
        "<table><tbody>",
        f"<tr><th>Sample</th><td>{escape(sample)}</td></tr>",
        f"<tr><th>Platform</th><td>{escape(summary.get('platform','?'))}</td></tr>",
        f"<tr><th>Reads classified</th>"
        f"<td>{_fmt_int(summary.get('total'))}</td></tr>",
        f"<tr><th>tecap version</th><td>{escape(__version__)}</td></tr>",
        f"<tr><th>schema</th><td>{escape(SCHEMA_VERSION)}</td></tr>",
        "</tbody></table>",
        "<h2>Executive summary</h2>",
        _executive_summary(summary),
        "<h2>Mechanism legend</h2>",
        _mechanism_legend_html(),
        "<h2>Mechanism breakdown</h2>",
        _maybe_embed_png(classify_png),
        f"<p class='caption'>{escape(PLOT_CAPTIONS['single'].format(sample=sample))}</p>",
        _classify_table(summary),
    ]

    pas_html = _pas_table(summary)
    if pas_html:
        parts += ["<h3>PAS hexamer split</h3>", pas_html]

    utr_html = _utr_table(summary)
    if utr_html:
        parts += ["<h3>UTR-length stratification</h3>", utr_html]

    if scatter_png:
        parts += [
            "<h3>MechA-correct: read length vs TE coverage</h3>",
            _maybe_embed_png(scatter_png),
            f"<p class='caption'>{escape(PLOT_CAPTIONS['mecha_scatter'])}</p>",
        ]

    if bc_summary is not None:
        window = bc_summary.get("window", 20)
        parts += [
            "<h2>Base composition downstream of cleavage</h2>",
            _maybe_embed_png(bc_png),
            f"<p class='caption'>{escape(PLOT_CAPTIONS['basecomp'].format(window=window))}</p>",
            "<h3>Per-bucket %A summary</h3>",
            _basecomp_table(bc_summary),
            "<h3>Bucket legend</h3>",
            _bucket_legend_html(),
        ]

    parts += [
        "<h2>Run command</h2>",
        f"<pre class='cmd'>{escape(cmd_line)}</pre>",
    ]

    body = "\n".join(parts)
    return _TEMPLATE.substitute(
        title=f"tecap report — {sample}",
        css=_CSS, body=body,
        version=__version__, schema=SCHEMA_VERSION,
    )


def build_compare_report(classify_jsons, basecomp_jsons=None, out_dir=None):
    out_dir = out_dir or os.path.dirname(os.path.abspath(classify_jsons[0]))
    classify_summaries = [read_json(p) for p in classify_jsons]
    samples = [s.get("sample", f"sample{i}") for i, s in enumerate(classify_summaries)]

    # Regenerate the cross-sample classify PNG into out_dir so the report is
    # always self-consistent with these JSONs.
    all_results = {s["sample"]: s for s in classify_summaries}
    plot_comparison_classify(all_results, out_dir)
    cmp_classify_png = os.path.join(out_dir, "comparison_terminal_exon.png")

    cmp_basecomp_png = None
    bc_summaries = None
    if basecomp_jsons:
        bc_summaries = [read_json(p) for p in basecomp_jsons]
        all_summaries = {s["sample"]: s for s in bc_summaries}
        window = bc_summaries[0].get("window", 20)
        plot_comparison_basecomp(all_summaries, out_dir, window)
        cmp_basecomp_png = os.path.join(out_dir, "comparison_basecomp.png")

    parts = [
        f"<h1>tecap comparison report — {escape(', '.join(samples))}</h1>",
        "<h2>Mechanism legend</h2>",
        _mechanism_legend_html(),
        "<h2>Mechanism breakdown across samples</h2>",
        _maybe_embed_png(cmp_classify_png),
        f"<p class='caption'>{escape(PLOT_CAPTIONS['comparison_classify'])}</p>",
    ]

    # Side-by-side classify tables.
    parts.append("<h3>Per-sample mechanism counts</h3>")
    for s in classify_summaries:
        parts.append(f"<h4>{escape(s.get('sample','?'))} "
                     f"(n={_fmt_int(s.get('total'))})</h4>")
        parts.append(_classify_table(s))

    if bc_summaries is not None:
        window = bc_summaries[0].get("window", 20)
        parts += [
            "<h2>Base composition: cross-sample</h2>",
            _maybe_embed_png(cmp_basecomp_png),
            f"<p class='caption'>{escape(PLOT_CAPTIONS['comparison_basecomp'].format(window=window))}</p>",
            "<h3>Bucket legend</h3>",
            _bucket_legend_html(),
        ]
        for s in bc_summaries:
            parts.append(f"<h4>{escape(s.get('sample','?'))}</h4>")
            parts.append(_basecomp_table(s))

    body = "\n".join(parts)
    return _TEMPLATE.substitute(
        title=f"tecap comparison — {', '.join(samples)}",
        css=_CSS, body=body,
        version=__version__, schema=SCHEMA_VERSION,
    )
